### ISSUE TITLE
Sync created resources upon edit of CustomResource

### ISSUE THREAD

**Issue by goncalo-oliveira** [openfaas/ingress-operator#39]
## Expected Behaviour
When adding/updating annotations to the `FunctionIngress`, these should be added/updated on the underlying `Ingress`.

## Current Behaviour
If the `FunctionIngress` and the underlying `Ingress` already exist, changes to the `FunctionIngress` annotations aren't passed to the underlying `Ingress`.

## Possible Solution
There's probably a validation on whether the ingress already exists that is bypassing the expected behaviour.

## Steps to Reproduce (for bugs)
1. Create a `FunctionIngress` with no custom annotations
2. Apply with `kubectl`
3. Add a custom annotation, for example `nginx.ingress.kubernetes.io/limit-connections: 10`
4. Apply with `kubectl`
5. Annotations aren't in the ingress

## Your Environment

* ingress-operator 0.6.5
* v1.18.8 (DigitalOcean)
* Linux

**Comment by alexellis** [comment]
This can be worked around easily by deleting and re-creating the FunctionIngress record, or editing the Ingress directly.

Would you be willing to work on a PR in the meantime?

**Comment by alexellis** [comment]
/add label: good first issue, help wanted

**Comment by alexellis** [comment]
/set title: Sync created resources upon edit of CustomResource

**Comment by alexellis** [comment]
Having another look at this, it seems that we already have support for this in the code?

Are you on the latest version of the build?

**Comment by alexellis** [comment]
https://github.com/openfaas/ingress-operator/blob/master/pkg/controller/controller.go#L308

**Comment by alexellis** [comment]
It seems like we only synchronise the spec, and not annotations. That is probably a deliberate design decision due to the way Kubernetes adds automated annotations to some objects.
