### ISSUE TITLE
Convert CI to GitHub Actions

### ISSUE THREAD

**Issue by alexellis** [openfaas/ingress-operator#41]
## Expected Behaviour

Convert CI to GitHub Actions

## Current Behaviour

We use Travis and need to move away

## Possible Solution

See the approach in https://github.com/openfaas/faas-netes/tree/master/.github

**Comment by developer-guy** [comment]
I am a volunteer for doing this issue.

**Comment by alexellis** [comment]
Thank you

**Comment by alexellis** [comment]
We still need a PR for this. It should match closely to the GitHub action from faas-netes or faas.
